### PR TITLE
2 copy code snippet button

### PR DESCRIPTION
**Pull request by altany**
I added a new component called CopyToClipboard.

I imported in your example.js to demo how it works.

I decided to pass to content to copy as children prop to CopyToClipboard but you can change it to a named prop if you prefer.

### CODE REVIEW

**Comment by drex44** [comment]
It works fine! nice job.

Thanks for PRs.

**Comment by drex44** [comment]
There's one more request if you're interested!
issue #4

**Comment by drex44** [comment]
Your merge is also live now!

**Comment by altany** [comment]
Perfect glad you like it!

**Pull request merged**
